---
argo-workflows:
  workflow:
    serviceAccount:
      create: true
      name: "argo-workflow"
    rbac:
      create: true
  server:
    authModes:
      - server
      - client
  controller:
    workflowNamespaces:
      - argo-workflows
