apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-workflows-role
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflowtaskresults
    verbs:
      - patch
      - list
      - update
      - create
  - apiGroups:
      - k6.io
    resources:
      - testruns
    verbs:
      - create
      - list
      - get
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-workflows-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-workflows-role
subjects:
  - kind: ServiceAccount
    name: argo-workflows-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-ui-token
  annotations:
    kubernetes.io/service-account.name: argo-workflows-sa
type: kubernetes.io/service-account-token